2020-07-10 09:14:47,362 DEBUG   MainThread:2634 [wandb_config.py:_load_defaults():132] no defaults not found in config-defaults.yaml
2020-07-10 09:14:47,590 DEBUG   MainThread:2634 [meta.py:_setup_code_git():49] probe for git information
2020-07-10 09:14:47,655 DEBUG   MainThread:2634 [run_manager.py:__init__():546] Initialized sync for odecropclassification/dzdc3d54
2020-07-10 09:14:47,669 INFO    MainThread:2634 [run_manager.py:wrap_existing_process():1148] wrapping existing process 2602
2020-07-10 09:14:47,674 WARNING MainThread:2634 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2020-07-10 09:14:47,761 INFO    MainThread:2634 [run_manager.py:init_run():927] system metrics and metadata threads started
2020-07-10 09:14:47,764 INFO    MainThread:2634 [run_manager.py:init_run():966] upserting run before process can begin, waiting at most 10 seconds
2020-07-10 09:14:48,048 INFO    Thread-15 :2634 [run_manager.py:_upsert_run():1055] saving pip packages
2020-07-10 09:14:48,057 INFO    Thread-15 :2634 [2020-07-10 09:14:55,698 INFO    MainThread:2580 [wandb_agent.py:run():209] Cleaning up finished run: dzdc3d54
2020-07-10 09:14:55,968 INFO    MainThread:2580 [wandb_agent.py:_process_command():256] Agent received command: run
2020-07-10 09:14:55,971 INFO    MainThread:2580 [wandb_agent.py:_command_run():286] Agent starting run with config:
	latents: 50
2020-07-10 09:14:56,007 DEBUG   MainThread:2580 [wandb_config.py:_load_defaults():128] wandb dir not provided, skipping defaults
2020-07-10 09:14:56,248 INFO    MainThread:2580 [wandb_agent.py:_command_run():325] About to run command: /usr/bin/env python3 run_models.py --niters=1 -n=11000000 -validn=300000 --dataset=swisscrop --swissdatatype=2_toplabels --val_freq=200 -b=400 --optimizer=adamax --ode-rnn --rnn-cell=gru --random-seed=6001 --stack-order=ode_rnn ode_rnn --lr=0.01 --lrdecay=0.99999 -g=100 -v=2 -u=255 --rec-layers=2 --topper=True --linear-topper=True -BN=True --step=2 --trunc=9 --latents=50
7-10 09:14:48,879 INFO    Thread-4  :2634 [run_manager.py:_on_file_created():680] file/dir created: /home/pf/pfstud/metzgern_PF/ODE_Nando/ODE_crop_Project/latent_ode-my_mod_hparam/wandb/run-20200710_071440-dzdc3d54/wandb-metadata.json
2020-07-10 09:14:48,884 INFO    Thread-4  :2634 [run_manager.py:_on_file_created():680] file/dir created: /home/pf/pfstud/metzgern_PF/ODE_Nando/ODE_crop_Project/latent_ode-my_mod_hparam/wandb/run-20200710_071440-dzdc3d54/output.log
2020-07-10 09:14:49,584 INFO    Thread-4  :2634 [run_manager.py:_on_file_modified():691] file/dir modified: /home/pf/pfstud/metzgern_PF/ODE_Nando/ODE_crop_Project/latent_ode-my_mod_hparam/wandb/run-20200710_071440-dzdc3d54/output.log
2020-07-10 09:14:50,077 INFO    MainThread:2634 [run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 1}
2020-07-10 09:14:50,082 INFO    MainThread:2634 [run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2020-07-10 09:14:50,086 INFO    MainThread:2634 [run_manager.py:shutdown():1071] shutting down system stats and metadata service
2020-07-10 09:14:50,590 INFO    Thread-4  :2634 [run_manager.py:_on_file_created():680] file/dir created: /home/pf/pfstud/metzgern_PF/ODE_Nando/ODE_crop_Project/latent_ode-my_mod_hparam/wandb/run-20200710_071440-dzdc3d54/wandb-events.jsonl
2020-07-10 09:14:50,769 INFO    MainThread:2634 [run_manager.py:shutdown():1085] stopping streaming files and file change observer
2020-07-10 09:14:51,591 INFO    Thread-4  :2634 [run_manager.py:_on_file_modified():691] file/dir modified: /home/pf/pfstud/metzgern_PF/ODE_Nando/ODE_crop_Project/latent_ode-my_mod_hparam/wandb/run-20200710_071440-dzdc3d54/wandb-metadata.json
2020-07-10 09:14:52,888 INFO    MainThread:2634 [run_manager.py:_sync_etc():1393] process only ran for 6 seconds, not syncing files
zdc3d54:run_manager.py:_on_file_modified():691] file/dir modified: /home/pf/pfstud/metzgern_PF/ODE_Nando/ODE_crop_Project/latent_ode-my_mod_hparam/wandb/run-20200710_071440-dzdc3d54/wandb-metadata.json
2020-07-10 09:14:52,888 INFO    MainThread:2634 [dzdc3d54:run_manager.py:_sync_etc():1393] process only ran for 6 seconds, not syncing files
