Lmod has detected the following error: The following module(s) are unknown:
"pytorch/1.4.0" "cuda/10.0.13"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "pytorch/1.4.0" "cuda/10.0.13"



/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod/run_models.py
run_models.py --niters 80 -n 300000 -b 500 -l 35 --dataset crop --ode-rnn --rec-dims 100 --rec-layers 4 --gen-layers 1 --units 500 --gru-units 50 --classif --ode-method eulers --random-seed 6002
  0%|          | 0/46080 [00:00<?, ?it/s]  0%|          | 0/46080 [00:00<?, ?it/s]
Couldn't import umap
Sampling dataset of 300000 training examples

Trainingdataset:
Dataset Crops
    Number of datapoints: 287858
    Root Location: data/Crops
    Reduce: average

Using Evaluationdataset:
Dataset Crops
    Number of datapoints: 55740
    Root Location: data/Crops
    Reduce: average

Traceback (most recent call last):
  File "run_models.py", line 295, in <module>
    train_res = model.compute_all_losses(batch_dict, n_traj_samples = 3, kl_coef = kl_coef)
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod/lib/base_models.py", line 132, in compute_all_losses
    mode = batch_dict["mode"])
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod/lib/ode_rnn.py", line 73, in get_reconstruction
    data_and_mask, truth_time_steps, run_backwards = False)
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod/lib/encoder_decoder.py", line 288, in run_odernn
    ode_sol = self.z0_diffeq_solver(prev_y, time_points)
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod/lib/diffeq_solver.py", line 41, in forward
    rtol=self.odeint_rtol, atol=self.odeint_atol, method = self.ode_method)
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/torchdiffeq/_impl/odeint.py", line 75, in odeint
    solver = SOLVERS[method](func, y0, rtol=rtol, atol=atol, **options)
KeyError: 'eulers'
