Lmod has detected the following error: The following module(s) are unknown:
"cuda/10.0.13" "pytorch/1.4.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "cuda/10.0.13" "pytorch/1.4.0"



wandb: Starting wandb agent üïµÔ∏è
2020-07-08 15:06:35,109 - wandb.wandb_agent - INFO - Running runs: []
2020-07-08 15:06:35,458 - wandb.wandb_agent - INFO - Agent received command: run
2020-07-08 15:06:35,458 - wandb.wandb_agent - INFO - Agent starting run with config:
	latents: 10
2020-07-08 15:06:35,677 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env /usr/bin/python train.py --niters 1 -n 11000000 -validn 300000 --dataset swisscrop --swissdatatype 2_toplabels --val_freq 200 -b 500 --optimizer adamax --ode-rnn --rnn-cell gru_small --random-seed 6001 --stack-order gru --lr 0.0076 -g 100 -u 255 --rec-layers 2 -v 2 --topper True -BN True --step 2 --trunc 9 --latents=10
/usr/bin/python: can't open file 'train.py': [Errno 2] No such file or directory
2020-07-08 15:06:40,691 - wandb.wandb_agent - INFO - Running runs: ['oxbktipu']
2020-07-08 15:06:40,693 - wandb.wandb_agent - INFO - Cleaning up finished run: oxbktipu
2020-07-08 15:06:41,013 - wandb.wandb_agent - INFO - Agent received command: run
2020-07-08 15:06:41,013 - wandb.wandb_agent - INFO - Agent starting run with config:
	latents: 20
2020-07-08 15:06:41,226 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env /usr/bin/python train.py --niters 1 -n 11000000 -validn 300000 --dataset swisscrop --swissdatatype 2_toplabels --val_freq 200 -b 500 --optimizer adamax --ode-rnn --rnn-cell gru_small --random-seed 6001 --stack-order gru --lr 0.0076 -g 100 -u 255 --rec-layers 2 -v 2 --topper True -BN True --step 2 --trunc 9 --latents=20
/usr/bin/python: can't open file 'train.py': [Errno 2] No such file or directory
2020-07-08 15:06:46,238 - wandb.wandb_agent - INFO - Running runs: ['zg3dwv9l']
2020-07-08 15:06:46,239 - wandb.wandb_agent - INFO - Cleaning up finished run: zg3dwv9l
2020-07-08 15:06:46,554 - wandb.wandb_agent - INFO - Agent received command: run
2020-07-08 15:06:46,555 - wandb.wandb_agent - INFO - Agent starting run with config:
	latents: 40
2020-07-08 15:06:46,764 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env /usr/bin/python train.py --niters 1 -n 11000000 -validn 300000 --dataset swisscrop --swissdatatype 2_toplabels --val_freq 200 -b 500 --optimizer adamax --ode-rnn --rnn-cell gru_small --random-seed 6001 --stack-order gru --lr 0.0076 -g 100 -u 255 --rec-layers 2 -v 2 --topper True -BN True --step 2 --trunc 9 --latents=40
/usr/bin/python: can't open file 'train.py': [Errno 2] No such file or directory
2020-07-08 15:06:51,777 - wandb.wandb_agent - INFO - Running runs: ['q6o0lg8a']
2020-07-08 15:06:51,779 - wandb.wandb_agent - ERROR - Detected 3 failed runs in the first 60 seconds, shutting down.
2020-07-08 15:06:51,779 - wandb.wandb_agent - INFO - To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
wandb: Terminating and syncing runs. Press ctrl-c to kill.
